# Generated by Django 4.1.6 on 2023-03-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(blank=True, choices=[('gerente', 'gerente'), ('recepção', 'recepção'), ('professor', 'professor')], default='', max_length=30, null=True),
        ),
    ]
