# Generated by Django 4.1.6 on 2023-03-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('segunda-feira', 'segunda-feira'), ('terça-feira', 'terça-feira'), ('quarta-feira', 'quartada-feira'), ('quinta-feira', 'quintaa-feira'), ('sexta-feira', 'sextaa-feira'), ('sábado-feira', 'sábadoda-feira'), ('domingo-feira', 'domingoa-feira')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='duracao_min',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fim',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='min_fim',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='min_inicio',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
