# Generated by Django 4.1.6 on 2023-03-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_remove_turma_horario_turma_dia_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='tt',
            field=models.TimeField(blank=True, default='', max_length=2, null=True),
        ),
    ]
