# Generated by Django 4.1.6 on 2023-03-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_turma_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='tt',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
