# Generated by Django 4.1.6 on 2023-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_alter_turma_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='tt',
            field=models.TimeField(default='00:00', verbose_name='teste'),
        ),
    ]
