# Generated by Django 4.1.6 on 2023-03-17 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_turma_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='tt',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='teste'),
        ),
    ]
