# Generated by Django 4.1.6 on 2023-03-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_turma_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='tt',
        ),
        migrations.AddField(
            model_name='turma',
            name='t',
            field=models.TimeField(null=True, verbose_name='teste'),
        ),
    ]
