# Generated by Django 4.1.6 on 2023-03-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_turma_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='t',
            field=models.TimeField(default='', null=True, verbose_name='teste'),
        ),
    ]
