# Generated by Django 4.1.6 on 2023-03-17 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_alter_turma_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='t',
            field=models.TimeField(default=datetime.time(0, 51, 12, 4008), null=True, verbose_name='teste'),
        ),
    ]
