# Generated by Django 4.1.6 on 2023-03-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_alter_turma_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='t',
        ),
    ]
