# Generated by Django 4.1.6 on 2023-03-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_remove_turma_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
